---
- name: Install Bacula Client
  yum: "name={{ item }} state=installed"
  loop:
   - bacula-client

- name: Configure Bacula Client
  copy:
    dest: "/etc/bacula/bacula-fd.conf"
    content: |
        Director {
        Name = bacula-dir
        Password = "Passwod"
        }
        FileDaemon {
        Name = aster
        FDport = 9102
        WorkingDirectory = /var/spool/bacula
        Pid Directory = /var/run
        Maximum Concurrent Jobs = 20
        FDAddress = {{ ENS160 }}
        }
        Messages {
        Name = Standard
        director = bacula-dir = all, !skipped, !restored
        }

- name: Start Bacula
  shell: bacula-fd

- name: Stop IPtables
  shell: systemctl stop firewalld

- name: Restore files from bacula
  local_action: shell ssh master@bacula "sudo echo restore client=Aster-Akado restoreclient=voip03 select current all done yes | /sbin/bconsole"
  when: "{{ restore }} == true"