---
# tasks file for install-asterisk

- name: Configure Time
  shell: "{{ item }}"
  loop:
       - timedatectl set-timezone Europe/Moscow 
       - ntpdate 1.ro.pool.ntp.org 

- name: Rename host
  hostname:
   name="{{ inventory_hostname }}"


- name: Remove existing install source dir
  file: "path={{ iasterisk_srcdir }} state=absent"

- name: Create install source dir
  file: "path={{ iasterisk_srcdir }} state=directory"

- name: Download and extract Asterisk source
  unarchive: "src={{ iasterisk_url }} dest={{ iasterisk_srcdir }} remote_src=yes extra_opts=--strip-components=1"
  when: "{{ restore_asterisk }} == true"
- name: Build Asterisk from tarball
  command: "{{ item }} chdir={{ iasterisk_srcdir }}"
  loop:
    - ./configure --libdir=/usr/lib64 --with-jansson-bundled
    - make menuselect.makeopts
    - make
    - make install
    - make config
    - make samples
  when: "{{ restore_asterisk }} == true"